services:

  db1:
    container_name: mysqldump-php-mysql-80
    image: mysql:8.0
    env_file:
      - .env.mysql
    volumes:
      - ./docker-entrypoint-initdb.d/mysql-8.0-init.sql:/docker-entrypoint-initdb.d/00-init.sql

  db2:
    container_name: mysqldump-php-mariadb-10
    image: mariadb:10.11
    env_file:
      - .env.mysql
    volumes:
      - ./docker-entrypoint-initdb.d/mariadb-init.sql:/docker-entrypoint-initdb.d/00-init.sql

  php81:
    container_name: mysqldump-php-81
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 81
    volumes:
      - .:/app
    depends_on:
      - db1
      - db2

  php82:
    container_name: mysqldump-php-82
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 82
    volumes:
      - .:/app
    depends_on:
      - db1
      - db2

  php83:
    container_name: mysqldump-php-83
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 83
    volumes:
      - .:/app
    depends_on:
      - db1
      - db2

  php84:
    container_name: mysqldump-php-84
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 84
    volumes:
      - .:/app
    depends_on:
      - db1
      - db2
