services:

  mysql:
    container_name: mysqldump-php-mysql-80
    image: mysql:8.0
    env_file:
      - .env.mysql
    volumes:
      - ./docker-entrypoint-initdb.d/mysql-init.sql:/docker-entrypoint-initdb.d/00-init.sql

  mariadb:
    container_name: mysqldump-php-mariadb-10
    image: mariadb:10.11
    env_file:
      - .env.mysql
    volumes:
      - ./docker-entrypoint-initdb.d/mariadb-init.sql:/docker-entrypoint-initdb.d/00-init.sql

  php82:
    container_name: mysqldump-php-82
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 82
    volumes:
      - .:/app
      - ./config/skip-ssl.cnf:/etc/my.cnf.d/skip-ssl.cnf
    depends_on:
      - mysql
      - mariadb

  php83:
    container_name: mysqldump-php-83
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 83
    volumes:
      - .:/app
      - ./config/skip-ssl.cnf:/etc/my.cnf.d/skip-ssl.cnf
    depends_on:
      - mysql
      - mariadb

  php84:
    container_name: mysqldump-php-84
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 84
    volumes:
      - .:/app
      - ./config/skip-ssl.cnf:/etc/my.cnf.d/skip-ssl.cnf
    depends_on:
      - mysql
      - mariadb

  php85:
    container_name: mysqldump-php-85
    build:
      context: .
      args:
        PHP_SHORT_VERSION: 85
    volumes:
      - .:/app
      - ./config/skip-ssl.cnf:/etc/my.cnf.d/skip-ssl.cnf
    depends_on:
      - mysql
      - mariadb
