CREATE USER IF NOT EXISTS 'example'@'%' IDENTIFIED WITH mysql_native_password BY 'example';
GRANT ALL ON *.* TO 'example'@'%';

CREATE DATABASE IF NOT EXISTS test001;
CREATE DATABASE IF NOT EXISTS test002;
CREATE DATABASE IF NOT EXISTS test005;
CREATE DATABASE IF NOT EXISTS test006a;
CREATE DATABASE IF NOT EXISTS test006b;
CREATE DATABASE IF NOT EXISTS test008;
CREATE DATABASE IF NOT EXISTS test009;
CREATE DATABASE IF NOT EXISTS test010;
CREATE DATABASE IF NOT EXISTS test011;
CREATE DATABASE IF NOT EXISTS test012;
CREATE DATABASE IF NOT EXISTS test014;
GRANT ALL PRIVILEGES ON test001.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test002.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test005.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test006a.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test006b.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test008.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test009.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test010.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test011.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test012.* TO 'example'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test014.* TO 'example'@'%' WITH GRANT OPTION;
GRANT PROCESS,SUPER,LOCK TABLES ON *.* TO 'example'@'%';

FLUSH PRIVILEGES;

SHOW databases;
