name: Run tests

on:
  push:
    branches:
      # Push events on main branch
      - main
      - php-8.4
  pull_request:

jobs:

  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # MySQL 8.0
          - os: ubuntu-latest
            database: 'mysql'
            database-version: '8.0'
            php-version: '8.1'
          - os: ubuntu-latest
            database: 'mysql'
            database-version: '8.0'
            php-version: '8.2'
          - os: ubuntu-latest
            database: 'mysql'
            database-version: '8.0'
            php-version: '8.3'
          - os: ubuntu-latest
            database: 'mysql'
            database-version: '8.0'
            php-version: '8.4'
          # MariaDB 10.11 LTS
          - os: ubuntu-20.04
            database: 'mariadb'
            database-version: '10.11'
            php-version: '8.1'
          - os: ubuntu-20.04
            database: 'mariadb'
            database-version: '10.11'
            php-version: '8.2'
          - os: ubuntu-20.04
            database: 'mariadb'
            database-version: '10.11'
            php-version: '8.3'
          - os: ubuntu-20.04
            database: 'mariadb'
            database-version: '10.11'
            php-version: '8.4'

    steps:

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          distribution: '${{ matrix.database }}'
          mysql-version: '${{ matrix.database-version }}'
          user: 'example'
          password: 'example'
          root-password: 'example'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json
        run: composer validate

      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction

      - name: Run PHPunit tests
        run: vendor/bin/phpunit

      - name: Create user and databases for testing
        run: mysql -u root -pexample < docker-entrypoint-initdb.d/${{ matrix.database }}-init.sql

      - name: Run test script
        run: tests/scripts/test.sh 127.0.0.1
